-- 1. Table: projects
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  company TEXT,
  button_text TEXT DEFAULT 'Visit Site',
  image TEXT NOT NULL,
  images TEXT[] DEFAULT '{}',
  url TEXT,
  description TEXT NOT NULL,
  modules TEXT[] DEFAULT '{}',
  tech_stack TEXT[] DEFAULT '{}',
  display_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Table: experiences
CREATE TABLE IF NOT EXISTS public.experiences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year TEXT NOT NULL,
  role TEXT NOT NULL,
  type TEXT NOT NULL,
  company TEXT NOT NULL,
  location TEXT NOT NULL,
  period TEXT NOT NULL,
  description TEXT NOT NULL,
  skills TEXT[] DEFAULT '{}',
  side TEXT DEFAULT 'left',
  display_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Table: contact_messages
CREATE TABLE IF NOT EXISTS public.contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experiences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

-- 5. Policies for Public Access
-- Allow anyone to read projects
CREATE POLICY "Allow public read projects"
  ON public.projects FOR SELECT
  USING (true);

-- Allow anyone to read experiences
CREATE POLICY "Allow public read experiences"
  ON public.experiences FOR SELECT
  USING (true);

-- Allow anyone to submit a contact message
CREATE POLICY "Allow public insert contact_messages"
  ON public.contact_messages FOR INSERT
  WITH CHECK (true);

-- 6. Storage Bucket for Project Images (optional/public)
INSERT INTO storage.buckets (id, name, public)
VALUES ('project-images', 'project-images', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Allow public read project images"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'project-images');

CREATE POLICY "Allow authenticated/service upload project images"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'project-images');
