-- 1. Table: projects
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  company TEXT,
  button_text TEXT DEFAULT 'Visit Site',
  image TEXT NOT NULL,
  images TEXT[] DEFAULT '{}',
  url TEXT,
  description TEXT NOT NULL,
  modules TEXT[] DEFAULT '{}',
  tech_stack TEXT[] DEFAULT '{}',
  display_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Optional: If you wish to have a dedicated is_academic column in Supabase projects table:
-- ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS is_academic BOOLEAN DEFAULT FALSE;

-- 2. Table: experiences
CREATE TABLE IF NOT EXISTS public.experiences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year TEXT NOT NULL,
  role TEXT NOT NULL,
  type TEXT NOT NULL,
  company TEXT NOT NULL,
  location TEXT NOT NULL,
  period TEXT NOT NULL,
  description TEXT NOT NULL,
  skills TEXT[] DEFAULT '{}',
  side TEXT DEFAULT 'left',
  display_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Table: contact_messages
CREATE TABLE IF NOT EXISTS public.contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT,
  message TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Table: profile (Single-Row Configuration)
CREATE TABLE IF NOT EXISTS public.profile (
  id INT PRIMARY KEY DEFAULT 1,
  greeting TEXT DEFAULT 'Hello, I''m',
  name TEXT NOT NULL DEFAULT 'Bintang Dimas',
  tagline TEXT NOT NULL DEFAULT 'Web Developer • UI/UX Designer • Graphic Designer • System Analyst',
  avatar_url TEXT DEFAULT '/me.jpg',
  about_text TEXT DEFAULT 'Information Systems graduate from Telkom University with a strong interest in information technology. Experienced in system design and development, UI/UX design, business process modeling, web development, and graphic design, gained through freelance work, volunteering, internships, and university projects. Proficient in Figma, Visio, Bizagi, VS Code, and Laragon, and adept at leveraging AI tools to optimize workflow efficiency. A disciplined professional with excellent time management skills, committed to continuous growth within the IT industry.',
  github_url TEXT DEFAULT 'https://github.com',
  linkedin_url TEXT DEFAULT 'https://linkedin.com',
  cv_url TEXT DEFAULT '/cv.pdf',
  education_school TEXT DEFAULT 'Telkom University Surabaya',
  education_degree TEXT DEFAULT 'Bachelor Degree of Information System',
  education_gpa TEXT DEFAULT '3.89 / 4.00',
  education_period TEXT DEFAULT '2020 - 2024',
  hard_skills TEXT[] DEFAULT '{Fullstack Developer, Graphic Design, UI/UX Design, Web Development, Data Entry, IT System Analyst, IT Support}',
  soft_skills TEXT[] DEFAULT '{Problem Solving, Teamwork & Collaboration, Time Management, Critical Thinking, Communication, Adaptability}',
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT single_profile_row CHECK (id = 1)
);

-- 5. Table: tech_tools
CREATE TABLE IF NOT EXISTS public.tech_tools (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label TEXT NOT NULL,
  category TEXT DEFAULT 'Development',
  color TEXT NOT NULL DEFAULT '#171717',
  icon_url TEXT NOT NULL,
  display_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Enable Row Level Security (RLS)
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experiences ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tech_tools ENABLE ROW LEVEL SECURITY;

-- 7. Policies for Public Access
CREATE POLICY "Allow public read projects" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Allow public read experiences" ON public.experiences FOR SELECT USING (true);
CREATE POLICY "Allow public insert contact_messages" ON public.contact_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read profile" ON public.profile FOR SELECT USING (true);
CREATE POLICY "Allow public read tech_tools" ON public.tech_tools FOR SELECT USING (true);

-- 8. Storage Bucket for Project & Profile Images
INSERT INTO storage.buckets (id, name, public)
VALUES ('project-images', 'project-images', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Allow public read project images"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'project-images');

CREATE POLICY "Allow authenticated/service upload project images"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'project-images');

-- Insert initial profile row if not exists
INSERT INTO public.profile (id) VALUES (1) ON CONFLICT (id) DO NOTHING;
